<a href="https://colab.research.google.com/github/diksha139/105StudentActivity/blob/main/ArrayOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Array Operations**

---



In [6]:
list1=[2,6,8,9,-3]

print(list1)

list2=[[1,2,-3], [True,6,"hi"],[8,3,-7]]
print(list2)
type(list2)





[2, 6, 8, 9, -3]
[[1, 2, -3], [True, 6, 'hi'], [8, 3, -7]]


list

In [21]:
import numpy as np

arr_2D= np.array([[1,2,3],[2,6,9],[7,9,11]])

print(arr_2D)
#method1 of accessing the elements
arr_2D[2][1]=12
print(arr_2D)

#method2 of accessing the elements

print(arr_2D[1,0])

arr_2D[1,0]=20

#type(arr_2D)

[[ 1  2  3]
 [ 2  6  9]
 [ 7  9 11]]
[[ 1  2  3]
 [ 2  6  9]
 [ 7 12 11]]
2
9
